services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - mdb_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress_shared:/var/www/html
    depends_on:
      - mariadb
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - WP_ADMIN_USER=admin
      - WP_ADMIN_PASSWORD=adminpass
      - WP_ADMIN_EMAIL=admin@tcoeffet.42.fr
    networks:
      - inception
  nginx:
    depends_on:
      - wordpress
    ports:
      - 443:443
    build: ./requirements/nginx
    image: inception_nginx
    container_name: nginx
    volumes:
      - wordpress_shared:/var/www/html
    networks:
      - inception

networks:
  inception:


volumes:
  mdb_db:
  wordpress_shared: