services:
  mariadb:
    build: ./requirements/mariadb/
    image: inception_mariadb
    volumes:
      - mdb_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  wordpress:
    build: ./requirements/wordpress
    image: inception_wordpress
    volumes:
      - wordpress_shared:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    networks:
      - inception
    restart: always
  nginx:
    depends_on:
      - wordpress
    ports:
      - 443:443
    build: ./requirements/nginx
    image: inception_nginx
    volumes:
      - wordpress_shared:/var/www/html
    networks:
      - inception
    restart: always

networks:
  inception:


volumes:
  mdb_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tcoeffet/data/mariadb
  wordpress_shared:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tcoeffet/data/wordpress